from .account_ui import AccountUI
from .home_ui import HomeUI
from .customer_ui import CustomerUI
from .waiter_ui import WaiterUI
from .category_ui import CategoryUi
from .meal_ui import MealUI
from .table_ui import TableUI
from .sidebar_ui import SidebarUI
from .login_ui import LoginUI
